# Generated by Django 3.2.6 on 2021-08-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
